import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { format, resolveConfig } from 'prettier';

const root = resolve(import.meta.dirname, '..');
const source = resolve(root, 'schemas/research/v1/skills.json');
const generated = resolve(root, 'packages/research/src/generated/skills.ts');
const browserCatalog = resolve(root, 'packages/research/public/skills.json');
const fixtureCatalog = resolve(root, 'test/fixtures/research/catalog.json');
const check = process.argv.includes('--check');
const skills = JSON.parse(await readFile(source, 'utf8'));
const prettier = (await resolveConfig(source)) ?? {};

const budget = (toolCalls, durationMs, inputTokens, outputTokens, sources, costUsd) => ({
  maxToolCalls: toolCalls,
  maxDurationMs: durationMs,
  maxInputTokens: inputTokens,
  maxOutputTokens: outputTokens,
  maxSources: sources,
  maxCostUsd: costUsd,
});

for (const skill of skills) {
  skill.defaultBudget = budget(12, 45_000, 24_000, 4_000, 20, 0.25);
  skill.maximumBudget = budget(60, 180_000, 120_000, 20_000, 80, 2);
}

const typescript = await format(
  `// Generated by scripts/research-assets.mjs. Do not edit.\nimport type { ResearchSkillManifest } from '../contracts.js';\n\nexport const GENERATED_RESEARCH_SKILLS = ${JSON.stringify(skills, null, 2)} as const satisfies readonly ResearchSkillManifest[];\n`,
  { ...prettier, filepath: generated },
);
const browser = await format(
  `${JSON.stringify(
    skills.map(({ id, name, description, version, taskType }) => ({
      id,
      name,
      description,
      version,
      taskType,
    })),
    null,
    2,
  )}\n`,
  { ...prettier, filepath: browserCatalog },
);
const fixture = await format(
  `${JSON.stringify(
    { schemaVersion: '1.0', generatedFrom: 'schemas/research/v1/skills.json', skills },
    null,
    2,
  )}\n`,
  { ...prettier, filepath: fixtureCatalog },
);

await sync(generated, typescript);
await sync(browserCatalog, browser);
await sync(fixtureCatalog, fixture);

async function sync(path, content) {
  if (!check) {
    await writeFile(path, content);
    return;
  }
  const current = await readFile(path, 'utf8').catch(() => '');
  if (current !== content) throw new Error(`${path} is stale; run npm run research:generate`);
}
