import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createHmac } from 'node:crypto';
import { resolve } from 'node:path';
import { format, resolveConfig } from 'prettier';

const root = resolve(import.meta.dirname, '..');
const schemaPath = resolve(root, 'schemas/webhooks/v1/envelope.schema.json');
const schema = JSON.parse(await readFile(schemaPath, 'utf8'));
const eventTypes = schema.properties.type.enum;
const version = schema.properties.schemaVersion.const;
const check = process.argv.includes('--check');

const ts = `// Generated by scripts/webhook-assets.mjs. Do not edit directly.
export const WEBHOOK_SCHEMA_VERSION = ${JSON.stringify(version)} as const;
export const WEBHOOK_EVENT_TYPES = ${JSON.stringify(eventTypes)} as const;
export type WebhookEventType = (typeof WEBHOOK_EVENT_TYPES)[number];

export interface WebhookResource {
  id: string;
  revision: number;
  url: string;
}

export interface WebhookEventData {
  summary: string;
  categories: string[];
  geographies: string[];
  entities: string[];
  assets: string[];
  impactPaths: string[];
  confidence?: number;
  language?: string;
  provenance: string[];
}

export interface WebhookEventEnvelope {
  id: string;
  type: WebhookEventType;
  schemaVersion: typeof WEBHOOK_SCHEMA_VERSION;
  occurredAt: string;
  publishedAt: string;
  tenantId: string;
  resource: WebhookResource;
  data: WebhookEventData;
  metadata: { producer: 'tnl'; traceId: string };
}
`;

const pythonValues = eventTypes.map((value) => `    ${JSON.stringify(value)},`).join('\n');
const python = `# Generated by scripts/webhook-assets.mjs. Do not edit directly.
from typing import Final, Literal

WEBHOOK_SCHEMA_VERSION: Final = ${JSON.stringify(version)}
WEBHOOK_EVENT_TYPES: Final = (
${pythonValues}
)
WebhookEventType = Literal[
${pythonValues}
]
`;

await output(resolve(root, 'packages/events/src/generated/events.ts'), ts, 'typescript');
await output(
  resolve(root, 'python/tnl_intelligence/src/tnl_intelligence/webhooks_generated.py'),
  python,
  'python',
);
const fixtureEvent = {
  id: 'evt_fixture123456789',
  type: 'intelligence.published',
  schemaVersion: version,
  occurredAt: '2026-07-18T12:00:00.000Z',
  publishedAt: '2026-07-18T12:00:02.000Z',
  tenantId: 'tenant-1',
  resource: {
    id: 'story-1',
    revision: 1,
    url: 'https://theneuralledger.com/story-1',
  },
  data: {
    summary: 'A synthetic event summary.',
    categories: ['Technology'],
    geographies: ['United States'],
    entities: ['Example Semiconductor'],
    assets: ['EXM'],
    impactPaths: ['supply-chain'],
    confidence: 0.82,
    language: 'en',
    provenance: ['https://example.com/source'],
  },
  metadata: { producer: 'tnl', traceId: 'trace-fixture-1' },
};
const rawBody = JSON.stringify(fixtureEvent);
const deliveryId = 'dlv_abcdefghijklmnop';
const timestamp = Math.floor(Date.parse(fixtureEvent.publishedAt) / 1_000);
const testKey = Buffer.alloc(32, 7);
const signature = createHmac('sha256', testKey)
  .update(Buffer.from(`v1.${timestamp}.${deliveryId}.`))
  .update(rawBody)
  .digest('hex');
await output(
  resolve(root, 'test/fixtures/webhooks/signed-published-v1.json'),
  JSON.stringify({
    event: fixtureEvent,
    rawBody,
    testKeyBase64url: testKey.toString('base64url'),
    headers: {
      'TNL-Webhook-Id': deliveryId,
      'TNL-Webhook-Timestamp': String(timestamp),
      'TNL-Webhook-Key-Id': 'key_current123',
      'TNL-Webhook-Signature': `v1=${signature}`,
      'TNL-Event-Type': fixtureEvent.type,
      'TNL-Event-Version': version,
    },
  }),
  'json',
);

console.log(check ? 'Webhook generated assets match the schema' : 'Webhook assets generated');

async function output(path, content, parser) {
  const options = { ...(await resolveConfig(path)), filepath: path, parser };
  const formatted = parser === 'python' ? content : await format(content, options);
  if (check) {
    const existing = await readFile(path, 'utf8').catch(() => '');
    if (existing !== formatted) throw new Error(`${path} is stale; run npm run webhooks:generate`);
    return;
  }
  await mkdir(resolve(path, '..'), { recursive: true });
  await writeFile(path, formatted, { mode: 0o644 });
}
