import assert from 'node:assert/strict';
import { access, readFile, readdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { describe, it } from 'node:test';
import Ajv2020 from 'ajv/dist/2020.js';
import { ADAPTER_WORKFLOWS } from '../../packages/adapters/dist/index.js';

const root = resolve(import.meta.dirname, '../..');
const plugin = resolve(root, 'integrations/openai/tnl-intelligence');

describe('OpenAI adapter bundle', () => {
  it('validates the plugin contract generated by the current plugin creator format', async () => {
    const schema = await json('schemas/adapters/openai-plugin.schema.json');
    const manifest = await json('integrations/openai/tnl-intelligence/.codex-plugin/plugin.json');
    const validate = new Ajv2020({ allErrors: true, strict: false }).compile(schema);
    assert.equal(validate(manifest), true, JSON.stringify(validate.errors));
    assert.equal(manifest.mcpServers, './.mcp.json');
    assert.equal(manifest.interface.capabilities.length, 6);
  });

  it('uses remote OAuth MCP only and does not invent an owner-issued app ID', async () => {
    const mcp = await json('integrations/openai/tnl-intelligence/.mcp.json');
    assert.deepEqual(mcp, {
      mcpServers: {
        'tnl-intelligence': { url: 'https://mcp.theneuralledger.com/mcp' },
      },
    });
    await assert.rejects(() => access(resolve(plugin, '.app.json')), /ENOENT/);
    const readme = await readFile(resolve(plugin, 'README.md'), 'utf8');
    assert.match(readme, /does not invent or commit that external ID/);
  });

  it('contains six shared skills and review-ready positive and negative cases', async () => {
    const skills = await readdir(resolve(plugin, 'skills'));
    assert.deepEqual(skills.sort(), ADAPTER_WORKFLOWS.map((item) => item.id).sort());
    const review = await json('integrations/openai/review/submission.json');
    assert.deepEqual(
      review.toolInventory.map((item) => item.toolName),
      ADAPTER_WORKFLOWS.map((item) => item.toolName),
    );
    assert.ok(review.toolInventory.every((item) => item.readOnly && !item.destructive));
    assert.ok(review.externalOwnerGates.every((item) => item.status !== 'complete'));
    const manual = await readFile(
      resolve(root, 'integrations/openai/review/manual-validation.md'),
      'utf8',
    );
    assert.match(manual, /autonomous trade execution/);
    assert.match(manual, /untrusted evidence/);
    assert.match(manual, /account's result ID/);
  });
});

async function json(path) {
  return JSON.parse(await readFile(resolve(root, path), 'utf8'));
}
