# Generated by scripts/webhook-assets.mjs. Do not edit directly.
from typing import Final, Literal

WEBHOOK_SCHEMA_VERSION: Final = "1.0"
WEBHOOK_EVENT_TYPES: Final = (
    "intelligence.published",
    "intelligence.updated",
    "intelligence.retracted",
    "intelligence.impact_changed",
    "digest.weekly_published",
    "subscription.test",
)
WebhookEventType = Literal[
    "intelligence.published",
    "intelligence.updated",
    "intelligence.retracted",
    "intelligence.impact_changed",
    "digest.weekly_published",
    "subscription.test",
]
